#pragma once

#define ECC_StickyProjectile ECollisionChannel::ECC_GameTraceChannel3
#define ECC_StickyGun ECollisionChannel::ECC_GameTraceChannel4
#define ECC_CharacterMesh ECollisionChannel::ECC_GameTraceChannel5
#define ECC_BaseShooter ECollisionChannel::ECC_GameTraceChannel6